import { HashMap } from "./hashmap.js";

const hashmap = new HashMap();

hashmap.set("apple", "red");
hashmap.set("apple", "Green");
hashmap.set("banana", "yellow");
hashmap.set("banana", "blue");
hashmap.set("carrot", "orange");
hashmap.set("carrot", "yellow");
hashmap.set("dog", "brown");
hashmap.set("elephant", "gray");
hashmap.set("frog", "green");
hashmap.set("grape", "purple");
hashmap.set("hat", "black");
hashmap.set("ice cream", "white");
hashmap.set("jacket", "blue");
hashmap.set("kite", "pink");
hashmap.set("lion", "golden");
hashmap.set("moon", "silver");
console.log(hashmap.length());
console.log(hashmap.has("frog"));
console.log(hashmap.get("grape"));
console.log(hashmap.has("hat"));
hashmap.remove("hat");
console.log(hashmap.has("hat"));
console.log(hashmap.keys());
console.log(hashmap.values());
console.log(hashmap.entries());
console.log(hashmap);
